"""empty message

Revision ID: 53a3737528e6
Revises: None
Create Date: 2016-07-06 21:14:47.108988

"""

# revision identifiers, used by Alembic.
revision = '53a3737528e6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=80), nullable=False),
    sa.Column('client', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client'),
    sa.UniqueConstraint('domain')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hosts')
    ### end Alembic commands ###
