"""empty message

Revision ID: ce3b56e8979b
Revises: 53a3737528e6
Create Date: 2016-07-06 21:33:29.977495

"""

# revision identifiers, used by Alembic.
revision = 'ce3b56e8979b'
down_revision = '53a3737528e6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('site', sa.String(length=80), nullable=False))
    op.drop_index('domain', table_name='hosts')
    op.create_unique_constraint(None, 'hosts', ['site'])
    op.drop_column('hosts', 'domain')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('domain', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'hosts', type_='unique')
    op.create_index('domain', 'hosts', ['domain'], unique=True)
    op.drop_column('hosts', 'site')
    ### end Alembic commands ###
